package pe.edu.upeu.milkflow.domain.model

enum class AccionUsuario {
    REGISTRAR_PRODUCTOR,
    ACTUALIZAR_PRODUCTOR,
    REGISTRAR_ACOPIADOR,
    REGISTRAR_ENTREGA_DIRECTA,
    REGISTRAR_LECHE_RECOGIDA,
    REGISTRAR_PRUEBA_CALIDAD,
    REGISTRAR_PROBLEMA_CALIDAD,
    SINCRONIZAR_REGISTROS,
    GESTIONAR_USUARIOS,
    CONSULTAR_AUDITORIA,
}
